
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int ka_lang_orth_chars[] = {
	2, 0x10d0, 0x10f0,	// range
};
unsigned int ka_lang_orth_size = 3;
#define KA_LANG_ORTH_SZ	3
