#!/bin/sh

die()
{
	echo $*
	exit 1
}

fc_lang_dir="@CMAKE_SOURCE_DIR@/fc-lang"
cat_srcdir="@CMAKE_CURRENT_SOURCE_DIR@/files"
cat_srcfile="@CMAKE_CURRENT_SOURCE_DIR@/fc-lang-cat.c"

orth_files=`ls ${fc_lang_dir}/*.orth`

# Firstly convert all *.orth files
cd "@CMAKE_CURRENT_SOURCE_DIR@/files/" || die
for f in ${orth_files}
do
	#echo $f
	@CMAKE_CURRENT_BINARY_DIR@/fc-lang_conv "${f}"
done
cd .. || die

# Header of "fc-lang-cat.c"
echo > "${cat_srcfile}"
echo "// This file is autogenerated from fc-lang database." >> "${cat_srcfile}"
echo "// https://www.freedesktop.org/wiki/Software/fontconfig/" >> "${cat_srcfile}"
echo "// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang" >> "${cat_srcfile}"
echo "// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw" >> "${cat_srcfile}"
echo >> "${cat_srcfile}"
echo "#include \"fc-lang-cat.h\"" >> "${cat_srcfile}"
echo >> "${cat_srcfile}"

# Then get list of all source files
orth_src_files=`ls "${cat_srcdir}"/*_orth.c`

# Insert '#include' for all sources
cat_sz=0
for f in ${orth_src_files}
do
	f=`basename ${f}`
	echo "#include \"files/${f}\"" >> "${cat_srcfile}"
	cat_sz=`expr ${cat_sz} + 1`
done
echo >> "${cat_srcfile}"

echo '#include <string.h>' >> "${cat_srcfile}"
echo >> "${cat_srcfile}"

echo "#define FC_LANG_CAT_SZ	${cat_sz}" >> "${cat_srcfile}"
echo "const struct fc_lang_catalog fc_lang_cat[] = {" >> "${cat_srcfile}"

# fill fc-lang table
for f in ${orth_src_files}
do
	lang_code=`basename "${f}" _orth.c`
	lang_code_lc=`echo ${lang_code} | tr '[:upper:]' '[:lower:]'`
	lang_code_uc=`echo ${lang_code} | tr '[:lower:]' '[:upper:]'`
	echo "	\"${lang_code_lc}\", ${lang_code_uc}_LANG_ORTH_SZ, ${lang_code_lc}_lang_orth_chars," >> "${cat_srcfile}"
done

echo "};" >> "${cat_srcfile}"
echo "const unsigned int fc_lang_cat_sz = ${cat_sz};" >> "${cat_srcfile}"
echo >> "${cat_srcfile}"

cat "@CMAKE_CURRENT_SOURCE_DIR@/fc-lang-cat_find.c.tmpl" >> "${cat_srcfile}"
echo >> "${cat_srcfile}"
